---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  # To enable Typha, set this to "calico-typha" *and* set a non-zero value for Typha replicas
  # below.  We recommend using Typha if you have more than 50 nodes. Above 100 nodes it is
  # essential.
{{- if .Values.config.typha.enabled }}
  typha_service_name: "calico-typha"
{{- else }}
  typha_service_name: "none"
{{- end }}
  # Configure the Calico backend to use.
  calico_backend: "{{ .Values.config.backend }}"
  # Configure the MTU to use for workload interfaces and tunnels.
  # - If Wireguard is enabled, set to your network MTU - 60
  # - Otherwise, if VXLAN or BPF mode is enabled, set to your network MTU - 50
  # - Otherwise, if IPIP is enabled, set to your network MTU - 20
  # - Otherwise, if not using any encapsulation, set to your network MTU.
  veth_mtu: "{{ .Values.config.veth_mtu }}"
  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "error",
        {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion }}
          "log_file_path": "/var/log/calico/cni/cni.log",
        {{- end }}
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
        {{- if .Values.config.ipam.subnet }}
          "ipam": {
        {{- if semverCompare ">= 1.16" .Capabilities.KubeVersion.GitVersion }}
            "type": "calico-ipam"
            "subnet": "{{ .Values.config.ipam.subnet }}"{{ if gt (len (split "," .Values.global.podCIDR)) 1 }},
            "assign_ipv4": "true",
            "assign_ipv6": "true"
        {{- end }}
        {{- else }}
            "type": "{{ .Values.config.ipam.type }}",
            "subnet": "{{ .Values.config.ipam.subnet }}"{{ if gt (len (split "," .Values.global.podCIDR)) 1 }},
            "assign_ipv4": "true",
            "assign_ipv6": "true"
            {{- end }}
        {{- end }}
          },
        {{- else }}
          "ipam": {
            "type": "{{ .Values.config.ipam.type }}"{{ if gt (len (split "," .Values.global.podCIDR)) 1 }},
            "assign_ipv4": "true",
            "assign_ipv6": "true"
            {{- end }}
          },
        {{- end }}
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
